sudo: required
services:
  - docker

before_install:
  - docker build -t thaiblockdocker/fibo-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thaiblockdocker/fibo-test npm run test -- --coverage

after_success:
  - docker build -t thaiblockdocker/fibo-client ./client
  - docker build -t thaiblockdocker/fibo-nginx ./nginx
  - docker build -t thaiblockdocker/fibo-server ./server
  - docker build -t thaiblockdocker/fibo-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push thaiblockdocker/fibo-client
  - docker push thaiblockdocker/fibo-nginx
  - docker push thaiblockdocker/fibo-server
  - docker push thaiblockdocker/fibo-worker
